version: "3.7"
services:
  saas-api:
    build:
      context: api
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 8000
    image: saas-api:dev
    container_name: saas-api
    networks:
      default:
        aliases:
          - api.saas.localhost
    env_file: ./api/.env
    environment:
      NODE_ENV: development
      URL_APP: http://app.saas.localhost:3000
      URL_API: http://api.saas.localhost:8000
      # see https://stackoverflow.com/a/22070413
      COOKIE_DOMAIN: .saas.localhost
      MONGO_URL: mongodb://saas:secret@saas-mongo:27017/saas
    ports:
      - "8000:8000"
    depends_on:
      - saas-mongo
    command: yarn start:container

  saas-app:
    build:
      context: app
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 3000
    image: saas-app:dev
    container_name: saas-app
    networks:
      default:
        aliases:
          - app.saas.localhost
    env_file: ./app/.env
    environment:
      NODE_ENV: development
      URL_APP: http://app.saas.localhost:3000
      URL_API: http://api.saas.localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - saas-api
    command: yarn start:container

  saas-mongo:
    image: mongo
    env_file: .env
    container_name: saas-mongo
    ports:
      - "27017:27017"
    volumes:
      # 20190601 - fix for https://github.com/docker-library/mongo/issues/329#issuecomment-460858099
      - ./mongo-user.sh:/docker-entrypoint-initdb.d/mongo-user.sh:ro
      - /tmp/saas-db:/data/db

  saas-mongoexp:
    image: mongo-express
    container_name: saas-mongoexp
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - saas-mongo

networks:
  default:
    driver: bridge
