version: "3.7"

services:
  api:
    build:
      context: api
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 8000
    image: saas-api:dev
    container_name: saas-api
    env_file: ./api/.env
    volumes:
      - ./api:/usr/src/api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: yarn dev

  app:
    build:
      context: app
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 3000
    image: saas-app:dev
    container_name: saas-app
    env_file: ./app/.env
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: yarn dev

  mongo:
    image: mongo
    env_file: .env
    container_name: saas-mongo
    ports:
      - "27017:27017"
    # 20190601 - fix for https://github.com/docker-library/mongo/issues/329#issuecomment-460858099
    volumes:
      - ./mongo-user.sh:/docker-entrypoint-initdb.d/mongo-user.sh:ro
      - /tmp/saas-db:/data/db
  # mongo-express is optional, only if you want to see mongodb data
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   env_file: .env
  #   depends_on:
  #     - mongo
