version: "3.7"
services:
  saas-api:
    build:
      context: api
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 8000
    image: saas-api:dev
    container_name: saas-api
    networks:
      default:
        aliases:
          - api.saas-dev
    env_file: ./api/.env
    # set the environment vard to use hostnames regardless of ./api/.env
    # so that it's configured for the docker network
    environment:
      NODE_ENV: development
      DEVELOPMENT_URL_APP: http://app.saas-dev:3000
      DEVELOPMENT_URL_API: http://api.saas-dev:8000
      DEVELOPMENT_COOKIE_DOMAIN: .saas-dev
      MONGO_URL_TEST: mongodb://saas:secret@saas-mongo:27017/saas
    ports:
      - "8000:8000"
    depends_on:
      - saas-mongo
    command: yarn start:container

  saas-app:
    build:
      context: app
      args:
        LOG_LEVEL: notice
        NODE_ENV: development
        PORT: 3000
    image: saas-app:dev
    container_name: saas-app
    networks:
      default:
        aliases:
          - app.saas-dev
    env_file: ./app/.env
    # set the environment vard to use hostnames regardless of ./app/.env
    # so that it's configured for the docker network
    environment:
      NODE_ENV: development
      DEVELOPMENT_URL_APP: http://app.saas-dev:3000
      DEVELOPMENT_URL_API: http://api.saas-dev:8000
    ports:
      - "3000:3000"
    depends_on:
      - saas-api
    command: yarn start:container

  saas-mongo:
    image: mongo
    env_file: .env
    container_name: saas-mongo
    ports:
      - "27017:27017"
    # 20190601 - fix for https://github.com/docker-library/mongo/issues/329#issuecomment-460858099
    volumes:
      - ./mongo-user.sh:/docker-entrypoint-initdb.d/mongo-user.sh:ro
      - /tmp/saas-db:/data/db
  # mongo-express is optional, only if you want to see mongodb data
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   env_file: .env
  #   depends_on:
  #     - mongo
networks:
  default:
    driver: bridge
